[tool.ruff]
target-version = "py39"
line-length = 88
select = ["E", "W"]  # シンプル・確実
ignore = ["E501", "W291", "W293"]

[tool.ruff.isort]
known-first-party = ["srta"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
exclude = ["tests/"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "--strict-markers --disable-warnings"

[tool.coverage.run]
source = ["srta"]
omit = ["*/tests/*", "setup.py"]

[tool.coverage.report]
precision = 2
show_missing = true
fail_under = 80
